language: c
script:
   - ./configure
   - omake -k

install:
   # Add PPA to download from.
   - sudo apt-add-repository -y ppa:pippijn/ppa
   - sudo apt-get update
   # Package dependencies.
   - sudo apt-get install --no-install-recommends `sed -e 's/#.*//' .dependencies`

# whitelist
branches:
   only:
      - master
      - /.*\/staging/
