{.state = 151, .token = 388, .msg = "undeclared type or missing comma "},
{.state = 80, .token = 388, .msg = "type has not been declared "},
{.state = 571, .token = -1, .msg = "missing ';' "},
{.state = 370, .token = -1, .msg = "missing ')' on parameter list "},
{.state = 76, .token = -1, .msg = "expecting IDENTIFIER or '{' "},
{.state = 22, .token = -1, .msg = "expecting IDENTIFIER or '{' "},
{.state = 27, .token = -1, .msg = "expecting PATTERN "},
{.state = 29, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 30, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 41, .token = -1, .msg = "expecting '(' EXPRESSION ')' "},
{.state = 43, .token = -1, .msg = "expecting 'union' "},
{.state = 44, .token = -1, .msg = "expecting 'datatype' "},
{.state = 50, .token = -1, .msg = "expecting '((' ATTRIBUTE_LIST '))' "},
{.state = 54, .token = -1, .msg = "expecting '(' PARAMETER_LIST ')' "},
{.state = 129, .token = -1, .msg = "expecting KIND "},
{.state = 138, .token = -1, .msg = "expecting KIND "},
{.state = 64, .token = -1, .msg = "expecting ';' or '{' "},
{.state = 65, .token = -1, .msg = "expecting ';' or '{' "},
{.state = 35, .token = -1, .msg = "expecting '<' or IDENTIFIER "},
{.state = 991, .token = -1, .msg = "missing '};' "},
{.state = 79, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 109, .token = -1, .msg = "expecting '(' "},
{.state = 106, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 110, .token = -1, .msg = "expecting PATTERN "},
{.state = 263, .token = -1, .msg = "expecting IDENTIFIER or extra ',' "},
{.state = 134, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 146, .token = -1, .msg = "missing '}' "},
{.state = 315, .token = -1, .msg = "missing '}' "},
{.state = 151, .token = -1, .msg = "missing ';' "},
{.state = 320, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 318, .token = -1, .msg = "expecting DECLARATION "},
{.state = 167, .token = 0, .msg = "missing '}' "},
{.state = 171, .token = -1, .msg = "expecting ']' or EXPRESSION "},
{.state = 516, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 378, .token = -1, .msg = "expecting TYPE "},
{.state = 624, .token = -1, .msg = "missing ')' "},
{.state = 376, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 622, .token = -1, .msg = "missing ')' "},
{.state = 189, .token = -1, .msg = "expecting TYPE "},
{.state = 388, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 195, .token = -1, .msg = "missing '}' "},
{.state = 255, .token = -1, .msg = "expecting TYPE_VARIABLE or '_' "},
{.state = 196, .token = -1, .msg = "expecting '(' EXPRESSION ')' or '( TYPE ')' "},
{.state = 426, .token = -1, .msg = "missing ')' "},
{.state = 199, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 200, .token = -1, .msg = "expecting INITIALIZER or EXPRESSION "},
{.state = 202, .token = -1, .msg = "expecting '(' EXPRESSION ') "},
{.state = 401, .token = -1, .msg = "expecting EXPRESSION ') "},
{.state = 644, .token = -1, .msg = "missing ') "},
{.state = 203, .token = -1, .msg = "expecting '(' EXPRESSION ',' EXPRESSION ') "},
{.state = 402, .token = -1, .msg = "expecting EXPRESSION ',' EXPRESSION ') "},
{.state = 645, .token = -1, .msg = "expecting ',' EXPRESSION ') "},
{.state = 819, .token = -1, .msg = "missing ')' "},
{.state = 207, .token = -1, .msg = "expecting '(' "},
{.state = 406, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 649, .token = -1, .msg = "expecting ',' "},
{.state = 823, .token = -1, .msg = "expecting 'sizeof(' TYPE ')' "},
{.state = 1052, .token = -1, .msg = "expecting TYPE "},
{.state = 1195, .token = -1, .msg = "missing ')' "},
{.state = 209, .token = -1, .msg = "expecting '(' "},
{.state = 408, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 651, .token = -1, .msg = "expecting ',' "},
{.state = 825, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 945, .token = -1, .msg = "expecting ',' "},
{.state = 1054, .token = -1, .msg = "expecting 'sizeof' "},
{.state = 1130, .token = -1, .msg = "expecting '(' "},
{.state = 1197, .token = -1, .msg = "expecting TYPE "},
{.state = 1230, .token = -1, .msg = "missing ')' "},
{.state = 211, .token = -1, .msg = "expecting '(' REGION_EXPRESSION ')' "},
{.state = 653, .token = -1, .msg = "missing ')' "},
{.state = 827, .token = -1, .msg = "expecting INITIALIZER or EXPRESSION "},
{.state = 213, .token = -1, .msg = "expecting '(' EXPRESSION ')' "},
{.state = 412, .token = -1, .msg = "expecting EXPRESSION ')' "},
{.state = 655, .token = -1, .msg = "missing ')' "},
{.state = 215, .token = -1, .msg = "expecting '(' TYPE ')' "},
{.state = 414, .token = -1, .msg = "expecting TYPE ')' "},
{.state = 657, .token = -1, .msg = "missing ')' "},
{.state = 216, .token = -1, .msg = "expecting '(' "},
{.state = 415, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 658, .token = -1, .msg = "expecting '.' IDENTIFIER or missing ')' "},
{.state = 833, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 596, .token = -1, .msg = "expecting TYPE_LIST, EXPRESSION_LIST, or ')' "},
{.state = 666, .token = -1, .msg = "expecting ')' "},
{.state = 670, .token = -1, .msg = "missing ':' EXPRESSION "},
{.state = 432, .token = -1, .msg = "missing EXPRESSION or extra '?' "},
{.state = 449, .token = -1, .msg = "missing EXPRESSION or extra operator "},
{.state = 453, .token = -1, .msg = "missing EXPRESSION or extra operator "},
{.state = 434, .token = -1, .msg = "missing EXPRESSION or extra '|' "},
{.state = 436, .token = -1, .msg = "missing EXPRESSION or extra '&' "},
{.state = 435, .token = -1, .msg = "missing EXPRESSION or extra '^' "},
{.state = 228, .token = -1, .msg = "missing EXPRESSION or extra '&' "},
{.state = 439, .token = -1, .msg = "missing EXPRESSION or extra operator "},
{.state = 444, .token = -1, .msg = "missing EXPRESSION or extra operator "},
{.state = 446, .token = -1, .msg = "missing EXPRESSION or extra '>>' "},
{.state = 445, .token = -1, .msg = "missing EXPRESSION or extra '<<' "},
{.state = 466, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 219, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 473, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 841, .token = 41, .msg = "extra ',' or missing argument "},
{.state = 685, .token = 59, .msg = "missing ')' "},
{.state = 472, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 468, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 688, .token = 62, .msg = "extra space not allowed in empty instantiation "},
{.state = 475, .token = -1, .msg = "expecting '<>' or '<' TYPE_LIST '>' "},
